### ISSUE TITLE
Calling `(stest/instrument)` after loading plugin gives StackOverflow

### ISSUE THREAD

**Issue by cjohansen** [borkdude/speculative-kaocha-plugin#2]
I tried the plugin on a project, and it worked fine, except when I used Orchestra to instrument my own functions. It seems to go on an infinite loop somehow:

```
java.lang.StackOverflowError
	at clojure.lang.Var.deref(Var.java:200)
	at clojure.lang.Var.get(Var.java:196)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:122)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at orchestra.spec.test$spec_checking_fn$conform_BANG___3110.invoke(test.clj:96)
	at orchestra.spec.test$spec_checking_fn$fn__3116.doInvoke(test.clj:124)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
...
```

**Comment by borkdude** [comment]
@cjohansen Are you sure this is Orchestra?

Are you calling `(stest/instrument)` anywhere? There are some specs that you should never instrument in speculative, due to limitations in clojure.spec. These specs do have the purpose for documentation and e.g. https://re-find.it.

See: https://github.com/borkdude/speculative/blob/master/blacklist.edn

**Comment by cjohansen** [comment]
My test helper included a call to `(orchestra.spec.test/instrument)`, which caused this error. Commenting out that line made the error go away. This does not happen when the speculative plugin is not involved. I haven't investigated deeper. My code has a few specs, but only for my own functions.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/speculative/commit/110ede0c8b17221d2b66d39541be1888cf185100
